a = input("digite algo: ")
print("o tipo primitivo desse valor é",type(a))
print("só tem espaços", a.isspace())
print(" é um número?", a.isnumeric())
print("é alfabetico?", a.isalpha())
print("é alfanúmerico?", a.isalnum())
print("esta em maiúscula?", a.isupper())
print("esta em minúscula", a.islower())
print("esta capitalizada?", a.istitle())
