n = str(input("digite seu nome completo:")).strip()
nome = n.split()
print("prazer em te conhecer!")
print("o primeiro nome é {}".format(nome[0]))
print("o segundo nome é {}".format(nome[len(nome)-1]))